# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clear_and_smooth_pb2 as clear__and__smooth__pb2


class ClearAndSmoothServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClearAndSmooth = channel.unary_unary(
                '/ClearAndSmoothService/ClearAndSmooth',
                request_serializer=clear__and__smooth__pb2.ClearAndSmoothRequest.SerializeToString,
                response_deserializer=clear__and__smooth__pb2.ClearAndSmoothResponse.FromString,
                )


class ClearAndSmoothServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClearAndSmooth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClearAndSmoothServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClearAndSmooth': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearAndSmooth,
                    request_deserializer=clear__and__smooth__pb2.ClearAndSmoothRequest.FromString,
                    response_serializer=clear__and__smooth__pb2.ClearAndSmoothResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClearAndSmoothService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClearAndSmoothService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClearAndSmooth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClearAndSmoothService/ClearAndSmooth',
            clear__and__smooth__pb2.ClearAndSmoothRequest.SerializeToString,
            clear__and__smooth__pb2.ClearAndSmoothResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
