# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python-service/image_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"python-service/image_service.proto\x12\x0cimageservice\"j\n\x19ListAvailableDatesRequest\x12\x18\n\x10geojson_features\x18\x01 \x03(\t\x12\r\n\x05\x62\x61nds\x18\x02 \x03(\t\x12\x12\n\nstart_date\x18\x03 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x04 \x01(\t\"5\n\x1aListAvailableDatesResponse\x12\x17\n\x0f\x61vailable_dates\x18\x01 \x03(\t\"M\n\x14GetBandValuesRequest\x12\x18\n\x10geojson_features\x18\x01 \x03(\t\x12\r\n\x05\x62\x61nds\x18\x02 \x03(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\"\x8e\x01\n\x15GetBandValuesResponse\x12\x44\n\tband_data\x18\x01 \x03(\x0b\x32\x31.imageservice.GetBandValuesResponse.BandDataEntry\x1a/\n\rBandDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c:\x02\x38\x01\x32\xd1\x01\n\x0cImageService\x12g\n\x12ListAvailableDates\x12\'.imageservice.ListAvailableDatesRequest\x1a(.imageservice.ListAvailableDatesResponse\x12X\n\rGetBandValues\x12\".imageservice.GetBandValuesRequest\x1a#.imageservice.GetBandValuesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'python_service.image_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETBANDVALUESRESPONSE_BANDDATAENTRY']._options = None
  _globals['_GETBANDVALUESRESPONSE_BANDDATAENTRY']._serialized_options = b'8\001'
  _globals['_LISTAVAILABLEDATESREQUEST']._serialized_start=52
  _globals['_LISTAVAILABLEDATESREQUEST']._serialized_end=158
  _globals['_LISTAVAILABLEDATESRESPONSE']._serialized_start=160
  _globals['_LISTAVAILABLEDATESRESPONSE']._serialized_end=213
  _globals['_GETBANDVALUESREQUEST']._serialized_start=215
  _globals['_GETBANDVALUESREQUEST']._serialized_end=292
  _globals['_GETBANDVALUESRESPONSE']._serialized_start=295
  _globals['_GETBANDVALUESRESPONSE']._serialized_end=437
  _globals['_GETBANDVALUESRESPONSE_BANDDATAENTRY']._serialized_start=390
  _globals['_GETBANDVALUESRESPONSE_BANDDATAENTRY']._serialized_end=437
  _globals['_IMAGESERVICE']._serialized_start=440
  _globals['_IMAGESERVICE']._serialized_end=649
# @@protoc_insertion_point(module_scope)
