# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_service_pb2 as python__service_dot_image__service__pb2


class ImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAvailableDates = channel.unary_unary(
                '/imageservice.ImageService/ListAvailableDates',
                request_serializer=python__service_dot_image__service__pb2.ListAvailableDatesRequest.SerializeToString,
                response_deserializer=python__service_dot_image__service__pb2.ListAvailableDatesResponse.FromString,
                )
        self.GetBandValues = channel.unary_unary(
                '/imageservice.ImageService/GetBandValues',
                request_serializer=python__service_dot_image__service__pb2.GetBandValuesRequest.SerializeToString,
                response_deserializer=python__service_dot_image__service__pb2.GetBandValuesResponse.FromString,
                )


class ImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAvailableDates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBandValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAvailableDates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvailableDates,
                    request_deserializer=python__service_dot_image__service__pb2.ListAvailableDatesRequest.FromString,
                    response_serializer=python__service_dot_image__service__pb2.ListAvailableDatesResponse.SerializeToString,
            ),
            'GetBandValues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBandValues,
                    request_deserializer=python__service_dot_image__service__pb2.GetBandValuesRequest.FromString,
                    response_serializer=python__service_dot_image__service__pb2.GetBandValuesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'imageservice.ImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAvailableDates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageservice.ImageService/ListAvailableDates',
            python__service_dot_image__service__pb2.ListAvailableDatesRequest.SerializeToString,
            python__service_dot_image__service__pb2.ListAvailableDatesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBandValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/imageservice.ImageService/GetBandValues',
            python__service_dot_image__service__pb2.GetBandValuesRequest.SerializeToString,
            python__service_dot_image__service__pb2.GetBandValuesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
