# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pest_clustering.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15pest_clustering.proto\"\xe8\x02\n\tDeltaData\x12\x0c\n\x04\x66\x61rm\x18\x01 \x01(\t\x12\x0c\n\x04plot\x18\x02 \x01(\t\x12\x11\n\tdelta_min\x18\x03 \x01(\x05\x12\x11\n\tdelta_max\x18\x04 \x01(\x05\x12\r\n\x05\x64\x65lta\x18\x05 \x01(\x05\x12\x12\n\nstart_date\x18\x06 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x07 \x01(\t\x12\t\n\x01x\x18\x08 \x01(\x05\x12\t\n\x01y\x18\t \x01(\x05\x12\x0c\n\x04ndre\x18\n \x01(\x01\x12\x0c\n\x04ndmi\x18\x0b \x01(\x01\x12\x0c\n\x04psri\x18\x0c \x01(\x01\x12\x0c\n\x04ndvi\x18\r \x01(\x01\x12\x17\n\x0fndre_derivative\x18\x0e \x01(\x01\x12\x17\n\x0fndmi_derivative\x18\x0f \x01(\x01\x12\x17\n\x0fpsri_derivative\x18\x10 \x01(\x01\x12\x17\n\x0fndvi_derivative\x18\x11 \x01(\x01\x12\r\n\x05label\x18\x12 \x01(\t\x12\x10\n\x08latitude\x18\x13 \x01(\x01\x12\x11\n\tlongitude\x18\x14 \x01(\x01\"=\n\x10PestSpreadSample\x12\x18\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\n.DeltaData\x12\x0f\n\x07\x63luster\x18\x02 \x01(\x05\"9\n\x17\x43lusterizeSpreadRequest\x12\x1e\n\ndelta_data\x18\x01 \x03(\x0b\x32\n.DeltaData\"J\n\x18\x43lusterizeSpreadResponse\x12.\n\x13pest_spread_samples\x18\x01 \x03(\x0b\x32\x11.PestSpreadSample2`\n\x15PestClusteringService\x12G\n\x10\x43lusterizeSpread\x12\x18.ClusterizeSpreadRequest\x1a\x19.ClusterizeSpreadResponseB\x0cZ\n/protobufsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pest_clustering_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n/protobufs'
  _globals['_DELTADATA']._serialized_start=26
  _globals['_DELTADATA']._serialized_end=386
  _globals['_PESTSPREADSAMPLE']._serialized_start=388
  _globals['_PESTSPREADSAMPLE']._serialized_end=449
  _globals['_CLUSTERIZESPREADREQUEST']._serialized_start=451
  _globals['_CLUSTERIZESPREADREQUEST']._serialized_end=508
  _globals['_CLUSTERIZESPREADRESPONSE']._serialized_start=510
  _globals['_CLUSTERIZESPREADRESPONSE']._serialized_end=584
  _globals['_PESTCLUSTERINGSERVICE']._serialized_start=586
  _globals['_PESTCLUSTERINGSERVICE']._serialized_end=682
# @@protoc_insertion_point(module_scope)
