# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pest_clustering_pb2 as pest__clustering__pb2


class PestClusteringServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClusterizeSpread = channel.unary_unary(
                '/PestClusteringService/ClusterizeSpread',
                request_serializer=pest__clustering__pb2.ClusterizeSpreadRequest.SerializeToString,
                response_deserializer=pest__clustering__pb2.ClusterizeSpreadResponse.FromString,
                )


class PestClusteringServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClusterizeSpread(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PestClusteringServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClusterizeSpread': grpc.unary_unary_rpc_method_handler(
                    servicer.ClusterizeSpread,
                    request_deserializer=pest__clustering__pb2.ClusterizeSpreadRequest.FromString,
                    response_serializer=pest__clustering__pb2.ClusterizeSpreadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PestClusteringService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PestClusteringService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClusterizeSpread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PestClusteringService/ClusterizeSpread',
            pest__clustering__pb2.ClusterizeSpreadRequest.SerializeToString,
            pest__clustering__pb2.ClusterizeSpreadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
