# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plot_pixels.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'plot_pixels.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11plot_pixels.proto\x12\x02ml\"\x1d\n\x05Pixel\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\xe8\x02\n\x11PlotPixelsRequest\x12-\n\x04NDVI\x18\x01 \x03(\x0b\x32\x1f.ml.PlotPixelsRequest.NDVIEntry\x12-\n\x04NDRE\x18\x02 \x03(\x0b\x32\x1f.ml.PlotPixelsRequest.NDREEntry\x12-\n\x04NDMI\x18\x03 \x03(\x0b\x32\x1f.ml.PlotPixelsRequest.NDMIEntry\x12\x19\n\x06pixels\x18\x04 \x03(\x0b\x32\t.ml.Pixel\x12\x13\n\x0b\x66orest_name\x18\x05 \x01(\t\x12\x0f\n\x07plot_id\x18\x06 \x01(\t\x1a+\n\tNDVIEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a+\n\tNDREEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a+\n\tNDMIEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"%\n\x12PlotPixelsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2P\n\x11PlotPixelsService\x12;\n\nPlotPixels\x12\x15.ml.PlotPixelsRequest\x1a\x16.ml.PlotPixelsResponseB\x0cZ\n/protobufsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plot_pixels_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n/protobufs'
  _globals['_PLOTPIXELSREQUEST_NDVIENTRY']._loaded_options = None
  _globals['_PLOTPIXELSREQUEST_NDVIENTRY']._serialized_options = b'8\001'
  _globals['_PLOTPIXELSREQUEST_NDREENTRY']._loaded_options = None
  _globals['_PLOTPIXELSREQUEST_NDREENTRY']._serialized_options = b'8\001'
  _globals['_PLOTPIXELSREQUEST_NDMIENTRY']._loaded_options = None
  _globals['_PLOTPIXELSREQUEST_NDMIENTRY']._serialized_options = b'8\001'
  _globals['_PIXEL']._serialized_start=25
  _globals['_PIXEL']._serialized_end=54
  _globals['_PLOTPIXELSREQUEST']._serialized_start=57
  _globals['_PLOTPIXELSREQUEST']._serialized_end=417
  _globals['_PLOTPIXELSREQUEST_NDVIENTRY']._serialized_start=284
  _globals['_PLOTPIXELSREQUEST_NDVIENTRY']._serialized_end=327
  _globals['_PLOTPIXELSREQUEST_NDREENTRY']._serialized_start=329
  _globals['_PLOTPIXELSREQUEST_NDREENTRY']._serialized_end=372
  _globals['_PLOTPIXELSREQUEST_NDMIENTRY']._serialized_start=374
  _globals['_PLOTPIXELSREQUEST_NDMIENTRY']._serialized_end=417
  _globals['_PLOTPIXELSRESPONSE']._serialized_start=419
  _globals['_PLOTPIXELSRESPONSE']._serialized_end=456
  _globals['_PLOTPIXELSSERVICE']._serialized_start=458
  _globals['_PLOTPIXELSSERVICE']._serialized_end=538
# @@protoc_insertion_point(module_scope)
