# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import plot_pixels_pb2 as plot__pixels__pb2


class PlotPixelsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlotPixels = channel.unary_unary(
                '/ml.PlotPixelsService/PlotPixels',
                request_serializer=plot__pixels__pb2.PlotPixelsRequest.SerializeToString,
                response_deserializer=plot__pixels__pb2.PlotPixelsResponse.FromString,
                )
        self.PlotDeltaPixels = channel.unary_unary(
                '/ml.PlotPixelsService/PlotDeltaPixels',
                request_serializer=plot__pixels__pb2.PlotDeltaPixelsRequest.SerializeToString,
                response_deserializer=plot__pixels__pb2.PlotDeltaPixelsResponse.FromString,
                )


class PlotPixelsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PlotPixels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlotDeltaPixels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlotPixelsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlotPixels': grpc.unary_unary_rpc_method_handler(
                    servicer.PlotPixels,
                    request_deserializer=plot__pixels__pb2.PlotPixelsRequest.FromString,
                    response_serializer=plot__pixels__pb2.PlotPixelsResponse.SerializeToString,
            ),
            'PlotDeltaPixels': grpc.unary_unary_rpc_method_handler(
                    servicer.PlotDeltaPixels,
                    request_deserializer=plot__pixels__pb2.PlotDeltaPixelsRequest.FromString,
                    response_serializer=plot__pixels__pb2.PlotDeltaPixelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml.PlotPixelsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PlotPixelsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PlotPixels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml.PlotPixelsService/PlotPixels',
            plot__pixels__pb2.PlotPixelsRequest.SerializeToString,
            plot__pixels__pb2.PlotPixelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PlotDeltaPixels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml.PlotPixelsService/PlotDeltaPixels',
            plot__pixels__pb2.PlotDeltaPixelsRequest.SerializeToString,
            plot__pixels__pb2.PlotDeltaPixelsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
