# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import run_model_pb2 as run__model__pb2


class RunModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunModel = channel.unary_unary(
                '/RunModelService/RunModel',
                request_serializer=run__model__pb2.RunModelRequest.SerializeToString,
                response_deserializer=run__model__pb2.RunModelResponse.FromString,
                )


class RunModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RunModel,
                    request_deserializer=run__model__pb2.RunModelRequest.FromString,
                    response_serializer=run__model__pb2.RunModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RunModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RunModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RunModelService/RunModel',
            run__model__pb2.RunModelRequest.SerializeToString,
            run__model__pb2.RunModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
