// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: run_model.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FinalData struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Weather       *FinalData_WeatherMetrics `protobuf:"bytes,1,opt,name=weather,proto3" json:"weather,omitempty"`
	Delta         *FinalData_DeltaData      `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"`
	CreatedAt     string                    `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalData) Reset() {
	*x = FinalData{}
	mi := &file_run_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalData) ProtoMessage() {}

func (x *FinalData) ProtoReflect() protoreflect.Message {
	mi := &file_run_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalData.ProtoReflect.Descriptor instead.
func (*FinalData) Descriptor() ([]byte, []int) {
	return file_run_model_proto_rawDescGZIP(), []int{0}
}

func (x *FinalData) GetWeather() *FinalData_WeatherMetrics {
	if x != nil {
		return x.Weather
	}
	return nil
}

func (x *FinalData) GetDelta() *FinalData_DeltaData {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *FinalData) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PixelResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Latitude      float64                `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,4,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Result        []*LabelProbability    `protobuf:"bytes,5,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PixelResult) Reset() {
	*x = PixelResult{}
	mi := &file_run_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PixelResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PixelResult) ProtoMessage() {}

func (x *PixelResult) ProtoReflect() protoreflect.Message {
	mi := &file_run_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PixelResult.ProtoReflect.Descriptor instead.
func (*PixelResult) Descriptor() ([]byte, []int) {
	return file_run_model_proto_rawDescGZIP(), []int{1}
}

func (x *PixelResult) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PixelResult) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PixelResult) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *PixelResult) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *PixelResult) GetResult() []*LabelProbability {
	if x != nil {
		return x.Result
	}
	return nil
}

type LabelProbability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Probability   float64                `protobuf:"fixed64,2,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelProbability) Reset() {
	*x = LabelProbability{}
	mi := &file_run_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelProbability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelProbability) ProtoMessage() {}

func (x *LabelProbability) ProtoReflect() protoreflect.Message {
	mi := &file_run_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelProbability.ProtoReflect.Descriptor instead.
func (*LabelProbability) Descriptor() ([]byte, []int) {
	return file_run_model_proto_rawDescGZIP(), []int{2}
}

func (x *LabelProbability) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LabelProbability) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

type RunModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*FinalData           `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunModelRequest) Reset() {
	*x = RunModelRequest{}
	mi := &file_run_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunModelRequest) ProtoMessage() {}

func (x *RunModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_run_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunModelRequest.ProtoReflect.Descriptor instead.
func (*RunModelRequest) Descriptor() ([]byte, []int) {
	return file_run_model_proto_rawDescGZIP(), []int{3}
}

func (x *RunModelRequest) GetData() []*FinalData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RunModelRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type RunModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*PixelResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunModelResponse) Reset() {
	*x = RunModelResponse{}
	mi := &file_run_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunModelResponse) ProtoMessage() {}

func (x *RunModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_run_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunModelResponse.ProtoReflect.Descriptor instead.
func (*RunModelResponse) Descriptor() ([]byte, []int) {
	return file_run_model_proto_rawDescGZIP(), []int{4}
}

func (x *RunModelResponse) GetResults() []*PixelResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type FinalData_WeatherMetrics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AvgTemperature     float64                `protobuf:"fixed64,1,opt,name=avg_temperature,json=avgTemperature,proto3" json:"avg_temperature,omitempty"`
	TempStdDev         float64                `protobuf:"fixed64,2,opt,name=temp_std_dev,json=tempStdDev,proto3" json:"temp_std_dev,omitempty"`
	AvgHumidity        float64                `protobuf:"fixed64,3,opt,name=avg_humidity,json=avgHumidity,proto3" json:"avg_humidity,omitempty"`
	HumidityStdDev     float64                `protobuf:"fixed64,4,opt,name=humidity_std_dev,json=humidityStdDev,proto3" json:"humidity_std_dev,omitempty"`
	TotalPrecipitation float64                `protobuf:"fixed64,5,opt,name=total_precipitation,json=totalPrecipitation,proto3" json:"total_precipitation,omitempty"`
	DryDaysConsecutive int32                  `protobuf:"varint,6,opt,name=dry_days_consecutive,json=dryDaysConsecutive,proto3" json:"dry_days_consecutive,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FinalData_WeatherMetrics) Reset() {
	*x = FinalData_WeatherMetrics{}
	mi := &file_run_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalData_WeatherMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalData_WeatherMetrics) ProtoMessage() {}

func (x *FinalData_WeatherMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_run_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalData_WeatherMetrics.ProtoReflect.Descriptor instead.
func (*FinalData_WeatherMetrics) Descriptor() ([]byte, []int) {
	return file_run_model_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FinalData_WeatherMetrics) GetAvgTemperature() float64 {
	if x != nil {
		return x.AvgTemperature
	}
	return 0
}

func (x *FinalData_WeatherMetrics) GetTempStdDev() float64 {
	if x != nil {
		return x.TempStdDev
	}
	return 0
}

func (x *FinalData_WeatherMetrics) GetAvgHumidity() float64 {
	if x != nil {
		return x.AvgHumidity
	}
	return 0
}

func (x *FinalData_WeatherMetrics) GetHumidityStdDev() float64 {
	if x != nil {
		return x.HumidityStdDev
	}
	return 0
}

func (x *FinalData_WeatherMetrics) GetTotalPrecipitation() float64 {
	if x != nil {
		return x.TotalPrecipitation
	}
	return 0
}

func (x *FinalData_WeatherMetrics) GetDryDaysConsecutive() int32 {
	if x != nil {
		return x.DryDaysConsecutive
	}
	return 0
}

type FinalData_DeltaData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Forest         string                 `protobuf:"bytes,1,opt,name=forest,proto3" json:"forest,omitempty"`
	Plot           string                 `protobuf:"bytes,2,opt,name=plot,proto3" json:"plot,omitempty"`
	DeltaMin       int32                  `protobuf:"varint,3,opt,name=delta_min,json=deltaMin,proto3" json:"delta_min,omitempty"`
	DeltaMax       int32                  `protobuf:"varint,4,opt,name=delta_max,json=deltaMax,proto3" json:"delta_max,omitempty"`
	Delta          int32                  `protobuf:"varint,5,opt,name=delta,proto3" json:"delta,omitempty"`
	StartDate      string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	X              int32                  `protobuf:"varint,8,opt,name=x,proto3" json:"x,omitempty"`
	Y              int32                  `protobuf:"varint,9,opt,name=y,proto3" json:"y,omitempty"`
	Ndre           float64                `protobuf:"fixed64,10,opt,name=ndre,proto3" json:"ndre,omitempty"`
	Ndmi           float64                `protobuf:"fixed64,11,opt,name=ndmi,proto3" json:"ndmi,omitempty"`
	Psri           float64                `protobuf:"fixed64,12,opt,name=psri,proto3" json:"psri,omitempty"`
	Ndvi           float64                `protobuf:"fixed64,13,opt,name=ndvi,proto3" json:"ndvi,omitempty"`
	NdreDerivative float64                `protobuf:"fixed64,14,opt,name=ndre_derivative,json=ndreDerivative,proto3" json:"ndre_derivative,omitempty"`
	NdmiDerivative float64                `protobuf:"fixed64,15,opt,name=ndmi_derivative,json=ndmiDerivative,proto3" json:"ndmi_derivative,omitempty"`
	PsriDerivative float64                `protobuf:"fixed64,16,opt,name=psri_derivative,json=psriDerivative,proto3" json:"psri_derivative,omitempty"`
	NdviDerivative float64                `protobuf:"fixed64,17,opt,name=ndvi_derivative,json=ndviDerivative,proto3" json:"ndvi_derivative,omitempty"`
	Label          string                 `protobuf:"bytes,18,opt,name=label,proto3" json:"label,omitempty"`
	Latitude       float64                `protobuf:"fixed64,19,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,20,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FinalData_DeltaData) Reset() {
	*x = FinalData_DeltaData{}
	mi := &file_run_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalData_DeltaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalData_DeltaData) ProtoMessage() {}

func (x *FinalData_DeltaData) ProtoReflect() protoreflect.Message {
	mi := &file_run_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalData_DeltaData.ProtoReflect.Descriptor instead.
func (*FinalData_DeltaData) Descriptor() ([]byte, []int) {
	return file_run_model_proto_rawDescGZIP(), []int{0, 1}
}

func (x *FinalData_DeltaData) GetForest() string {
	if x != nil {
		return x.Forest
	}
	return ""
}

func (x *FinalData_DeltaData) GetPlot() string {
	if x != nil {
		return x.Plot
	}
	return ""
}

func (x *FinalData_DeltaData) GetDeltaMin() int32 {
	if x != nil {
		return x.DeltaMin
	}
	return 0
}

func (x *FinalData_DeltaData) GetDeltaMax() int32 {
	if x != nil {
		return x.DeltaMax
	}
	return 0
}

func (x *FinalData_DeltaData) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *FinalData_DeltaData) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *FinalData_DeltaData) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *FinalData_DeltaData) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FinalData_DeltaData) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *FinalData_DeltaData) GetNdre() float64 {
	if x != nil {
		return x.Ndre
	}
	return 0
}

func (x *FinalData_DeltaData) GetNdmi() float64 {
	if x != nil {
		return x.Ndmi
	}
	return 0
}

func (x *FinalData_DeltaData) GetPsri() float64 {
	if x != nil {
		return x.Psri
	}
	return 0
}

func (x *FinalData_DeltaData) GetNdvi() float64 {
	if x != nil {
		return x.Ndvi
	}
	return 0
}

func (x *FinalData_DeltaData) GetNdreDerivative() float64 {
	if x != nil {
		return x.NdreDerivative
	}
	return 0
}

func (x *FinalData_DeltaData) GetNdmiDerivative() float64 {
	if x != nil {
		return x.NdmiDerivative
	}
	return 0
}

func (x *FinalData_DeltaData) GetPsriDerivative() float64 {
	if x != nil {
		return x.PsriDerivative
	}
	return 0
}

func (x *FinalData_DeltaData) GetNdviDerivative() float64 {
	if x != nil {
		return x.NdviDerivative
	}
	return 0
}

func (x *FinalData_DeltaData) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *FinalData_DeltaData) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *FinalData_DeltaData) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_run_model_proto protoreflect.FileDescriptor

const file_run_model_proto_rawDesc = "" +
	"\n" +
	"\x0frun_model.proto\"\xbd\a\n" +
	"\tFinalData\x123\n" +
	"\aweather\x18\x01 \x01(\v2\x19.FinalData.WeatherMetricsR\aweather\x12*\n" +
	"\x05delta\x18\x02 \x01(\v2\x14.FinalData.DeltaDataR\x05delta\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x1a\x8b\x02\n" +
	"\x0eWeatherMetrics\x12'\n" +
	"\x0favg_temperature\x18\x01 \x01(\x01R\x0eavgTemperature\x12 \n" +
	"\ftemp_std_dev\x18\x02 \x01(\x01R\n" +
	"tempStdDev\x12!\n" +
	"\favg_humidity\x18\x03 \x01(\x01R\vavgHumidity\x12(\n" +
	"\x10humidity_std_dev\x18\x04 \x01(\x01R\x0ehumidityStdDev\x12/\n" +
	"\x13total_precipitation\x18\x05 \x01(\x01R\x12totalPrecipitation\x120\n" +
	"\x14dry_days_consecutive\x18\x06 \x01(\x05R\x12dryDaysConsecutive\x1a\xa1\x04\n" +
	"\tDeltaData\x12\x16\n" +
	"\x06forest\x18\x01 \x01(\tR\x06forest\x12\x12\n" +
	"\x04plot\x18\x02 \x01(\tR\x04plot\x12\x1b\n" +
	"\tdelta_min\x18\x03 \x01(\x05R\bdeltaMin\x12\x1b\n" +
	"\tdelta_max\x18\x04 \x01(\x05R\bdeltaMax\x12\x14\n" +
	"\x05delta\x18\x05 \x01(\x05R\x05delta\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\x12\f\n" +
	"\x01x\x18\b \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\t \x01(\x05R\x01y\x12\x12\n" +
	"\x04ndre\x18\n" +
	" \x01(\x01R\x04ndre\x12\x12\n" +
	"\x04ndmi\x18\v \x01(\x01R\x04ndmi\x12\x12\n" +
	"\x04psri\x18\f \x01(\x01R\x04psri\x12\x12\n" +
	"\x04ndvi\x18\r \x01(\x01R\x04ndvi\x12'\n" +
	"\x0fndre_derivative\x18\x0e \x01(\x01R\x0endreDerivative\x12'\n" +
	"\x0fndmi_derivative\x18\x0f \x01(\x01R\x0endmiDerivative\x12'\n" +
	"\x0fpsri_derivative\x18\x10 \x01(\x01R\x0epsriDerivative\x12'\n" +
	"\x0fndvi_derivative\x18\x11 \x01(\x01R\x0endviDerivative\x12\x14\n" +
	"\x05label\x18\x12 \x01(\tR\x05label\x12\x1a\n" +
	"\blatitude\x18\x13 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x14 \x01(\x01R\tlongitude\"\x8e\x01\n" +
	"\vPixelResult\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x1a\n" +
	"\blatitude\x18\x03 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x04 \x01(\x01R\tlongitude\x12)\n" +
	"\x06result\x18\x05 \x03(\v2\x11.LabelProbabilityR\x06result\"J\n" +
	"\x10LabelProbability\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12 \n" +
	"\vprobability\x18\x02 \x01(\x01R\vprobability\"G\n" +
	"\x0fRunModelRequest\x12\x1e\n" +
	"\x04data\x18\x01 \x03(\v2\n" +
	".FinalDataR\x04data\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\":\n" +
	"\x10RunModelResponse\x12&\n" +
	"\aresults\x18\x01 \x03(\v2\f.PixelResultR\aresults2B\n" +
	"\x0fRunModelService\x12/\n" +
	"\bRunModel\x12\x10.RunModelRequest\x1a\x11.RunModelResponseBJZHgithub.com/forest-guardian/forest-guardian-api-poc/internal/ml/protobufsb\x06proto3"

var (
	file_run_model_proto_rawDescOnce sync.Once
	file_run_model_proto_rawDescData []byte
)

func file_run_model_proto_rawDescGZIP() []byte {
	file_run_model_proto_rawDescOnce.Do(func() {
		file_run_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_run_model_proto_rawDesc), len(file_run_model_proto_rawDesc)))
	})
	return file_run_model_proto_rawDescData
}

var file_run_model_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_run_model_proto_goTypes = []any{
	(*FinalData)(nil),                // 0: FinalData
	(*PixelResult)(nil),              // 1: PixelResult
	(*LabelProbability)(nil),         // 2: LabelProbability
	(*RunModelRequest)(nil),          // 3: RunModelRequest
	(*RunModelResponse)(nil),         // 4: RunModelResponse
	(*FinalData_WeatherMetrics)(nil), // 5: FinalData.WeatherMetrics
	(*FinalData_DeltaData)(nil),      // 6: FinalData.DeltaData
}
var file_run_model_proto_depIdxs = []int32{
	5, // 0: FinalData.weather:type_name -> FinalData.WeatherMetrics
	6, // 1: FinalData.delta:type_name -> FinalData.DeltaData
	2, // 2: PixelResult.result:type_name -> LabelProbability
	0, // 3: RunModelRequest.data:type_name -> FinalData
	1, // 4: RunModelResponse.results:type_name -> PixelResult
	3, // 5: RunModelService.RunModel:input_type -> RunModelRequest
	4, // 6: RunModelService.RunModel:output_type -> RunModelResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_run_model_proto_init() }
func file_run_model_proto_init() {
	if File_run_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_run_model_proto_rawDesc), len(file_run_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_run_model_proto_goTypes,
		DependencyIndexes: file_run_model_proto_depIdxs,
		MessageInfos:      file_run_model_proto_msgTypes,
	}.Build()
	File_run_model_proto = out.File
	file_run_model_proto_goTypes = nil
	file_run_model_proto_depIdxs = nil
}
