// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: pest_clustering.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PestClusteringService_ClusterizeSpread_FullMethodName = "/PestClusteringService/ClusterizeSpread"
)

// PestClusteringServiceClient is the client API for PestClusteringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PestClusteringServiceClient interface {
	ClusterizeSpread(ctx context.Context, in *ClusterizeSpreadRequest, opts ...grpc.CallOption) (*ClusterizeSpreadResponse, error)
}

type pestClusteringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPestClusteringServiceClient(cc grpc.ClientConnInterface) PestClusteringServiceClient {
	return &pestClusteringServiceClient{cc}
}

func (c *pestClusteringServiceClient) ClusterizeSpread(ctx context.Context, in *ClusterizeSpreadRequest, opts ...grpc.CallOption) (*ClusterizeSpreadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterizeSpreadResponse)
	err := c.cc.Invoke(ctx, PestClusteringService_ClusterizeSpread_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PestClusteringServiceServer is the server API for PestClusteringService service.
// All implementations must embed UnimplementedPestClusteringServiceServer
// for forward compatibility.
type PestClusteringServiceServer interface {
	ClusterizeSpread(context.Context, *ClusterizeSpreadRequest) (*ClusterizeSpreadResponse, error)
	mustEmbedUnimplementedPestClusteringServiceServer()
}

// UnimplementedPestClusteringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPestClusteringServiceServer struct{}

func (UnimplementedPestClusteringServiceServer) ClusterizeSpread(context.Context, *ClusterizeSpreadRequest) (*ClusterizeSpreadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClusterizeSpread not implemented")
}
func (UnimplementedPestClusteringServiceServer) mustEmbedUnimplementedPestClusteringServiceServer() {}
func (UnimplementedPestClusteringServiceServer) testEmbeddedByValue()                               {}

// UnsafePestClusteringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PestClusteringServiceServer will
// result in compilation errors.
type UnsafePestClusteringServiceServer interface {
	mustEmbedUnimplementedPestClusteringServiceServer()
}

func RegisterPestClusteringServiceServer(s grpc.ServiceRegistrar, srv PestClusteringServiceServer) {
	// If the following call pancis, it indicates UnimplementedPestClusteringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PestClusteringService_ServiceDesc, srv)
}

func _PestClusteringService_ClusterizeSpread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterizeSpreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PestClusteringServiceServer).ClusterizeSpread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PestClusteringService_ClusterizeSpread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PestClusteringServiceServer).ClusterizeSpread(ctx, req.(*ClusterizeSpreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PestClusteringService_ServiceDesc is the grpc.ServiceDesc for PestClusteringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PestClusteringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PestClusteringService",
	HandlerType: (*PestClusteringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClusterizeSpread",
			Handler:    _PestClusteringService_ClusterizeSpread_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pest_clustering.proto",
}
