// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: go-service/internal/ml/protobufs/image_service.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListAvailableDatesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GeojsonFeatures []string               `protobuf:"bytes,1,rep,name=geojson_features,json=geojsonFeatures,proto3" json:"geojson_features,omitempty"` // Array of GeoJSON geometries as strings
	Bands           []string               `protobuf:"bytes,2,rep,name=bands,proto3" json:"bands,omitempty"`                                            // List of band names (e.g., "B02", "B04")
	StartDate       string                 `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`                   // "YYYY-MM-DD"
	EndDate         string                 `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`                         // "YYYY-MM-DD"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAvailableDatesRequest) Reset() {
	*x = ListAvailableDatesRequest{}
	mi := &file_go_service_internal_ml_protobufs_image_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableDatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableDatesRequest) ProtoMessage() {}

func (x *ListAvailableDatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_service_internal_ml_protobufs_image_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableDatesRequest.ProtoReflect.Descriptor instead.
func (*ListAvailableDatesRequest) Descriptor() ([]byte, []int) {
	return file_go_service_internal_ml_protobufs_image_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListAvailableDatesRequest) GetGeojsonFeatures() []string {
	if x != nil {
		return x.GeojsonFeatures
	}
	return nil
}

func (x *ListAvailableDatesRequest) GetBands() []string {
	if x != nil {
		return x.Bands
	}
	return nil
}

func (x *ListAvailableDatesRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListAvailableDatesRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type ListAvailableDatesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvailableDates []string               `protobuf:"bytes,1,rep,name=available_dates,json=availableDates,proto3" json:"available_dates,omitempty"` // List of available dates in "YYYY-MM-DD"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListAvailableDatesResponse) Reset() {
	*x = ListAvailableDatesResponse{}
	mi := &file_go_service_internal_ml_protobufs_image_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAvailableDatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAvailableDatesResponse) ProtoMessage() {}

func (x *ListAvailableDatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_service_internal_ml_protobufs_image_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAvailableDatesResponse.ProtoReflect.Descriptor instead.
func (*ListAvailableDatesResponse) Descriptor() ([]byte, []int) {
	return file_go_service_internal_ml_protobufs_image_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListAvailableDatesResponse) GetAvailableDates() []string {
	if x != nil {
		return x.AvailableDates
	}
	return nil
}

type GetBandValuesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GeojsonFeatures []string               `protobuf:"bytes,1,rep,name=geojson_features,json=geojsonFeatures,proto3" json:"geojson_features,omitempty"` // Array of GeoJSON geometries as strings
	Bands           []string               `protobuf:"bytes,2,rep,name=bands,proto3" json:"bands,omitempty"`
	Date            string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"` // "YYYY-MM-DD"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBandValuesRequest) Reset() {
	*x = GetBandValuesRequest{}
	mi := &file_go_service_internal_ml_protobufs_image_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBandValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBandValuesRequest) ProtoMessage() {}

func (x *GetBandValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_service_internal_ml_protobufs_image_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBandValuesRequest.ProtoReflect.Descriptor instead.
func (*GetBandValuesRequest) Descriptor() ([]byte, []int) {
	return file_go_service_internal_ml_protobufs_image_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBandValuesRequest) GetGeojsonFeatures() []string {
	if x != nil {
		return x.GeojsonFeatures
	}
	return nil
}

func (x *GetBandValuesRequest) GetBands() []string {
	if x != nil {
		return x.Bands
	}
	return nil
}

func (x *GetBandValuesRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetBandValuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BandData      map[string][]byte      `protobuf:"bytes,1,rep,name=band_data,json=bandData,proto3" json:"band_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBandValuesResponse) Reset() {
	*x = GetBandValuesResponse{}
	mi := &file_go_service_internal_ml_protobufs_image_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBandValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBandValuesResponse) ProtoMessage() {}

func (x *GetBandValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_service_internal_ml_protobufs_image_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBandValuesResponse.ProtoReflect.Descriptor instead.
func (*GetBandValuesResponse) Descriptor() ([]byte, []int) {
	return file_go_service_internal_ml_protobufs_image_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetBandValuesResponse) GetBandData() map[string][]byte {
	if x != nil {
		return x.BandData
	}
	return nil
}

var File_go_service_internal_ml_protobufs_image_service_proto protoreflect.FileDescriptor

const file_go_service_internal_ml_protobufs_image_service_proto_rawDesc = "" +
	"\n" +
	"4go-service/internal/ml/protobufs/image_service.proto\x12\fimageservice\"\x96\x01\n" +
	"\x19ListAvailableDatesRequest\x12)\n" +
	"\x10geojson_features\x18\x01 \x03(\tR\x0fgeojsonFeatures\x12\x14\n" +
	"\x05bands\x18\x02 \x03(\tR\x05bands\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\tR\aendDate\"E\n" +
	"\x1aListAvailableDatesResponse\x12'\n" +
	"\x0favailable_dates\x18\x01 \x03(\tR\x0eavailableDates\"k\n" +
	"\x14GetBandValuesRequest\x12)\n" +
	"\x10geojson_features\x18\x01 \x03(\tR\x0fgeojsonFeatures\x12\x14\n" +
	"\x05bands\x18\x02 \x03(\tR\x05bands\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"\xa4\x01\n" +
	"\x15GetBandValuesResponse\x12N\n" +
	"\tband_data\x18\x01 \x03(\v21.imageservice.GetBandValuesResponse.BandDataEntryR\bbandData\x1a;\n" +
	"\rBandDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x012\xd1\x01\n" +
	"\fImageService\x12g\n" +
	"\x12ListAvailableDates\x12'.imageservice.ListAvailableDatesRequest\x1a(.imageservice.ListAvailableDatesResponse\x12X\n" +
	"\rGetBandValues\x12\".imageservice.GetBandValuesRequest\x1a#.imageservice.GetBandValuesResponseBJZHgithub.com/forest-guardian/forest-guardian-api-poc/internal/ml/protobufsb\x06proto3"

var (
	file_go_service_internal_ml_protobufs_image_service_proto_rawDescOnce sync.Once
	file_go_service_internal_ml_protobufs_image_service_proto_rawDescData []byte
)

func file_go_service_internal_ml_protobufs_image_service_proto_rawDescGZIP() []byte {
	file_go_service_internal_ml_protobufs_image_service_proto_rawDescOnce.Do(func() {
		file_go_service_internal_ml_protobufs_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_service_internal_ml_protobufs_image_service_proto_rawDesc), len(file_go_service_internal_ml_protobufs_image_service_proto_rawDesc)))
	})
	return file_go_service_internal_ml_protobufs_image_service_proto_rawDescData
}

var file_go_service_internal_ml_protobufs_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_go_service_internal_ml_protobufs_image_service_proto_goTypes = []any{
	(*ListAvailableDatesRequest)(nil),  // 0: imageservice.ListAvailableDatesRequest
	(*ListAvailableDatesResponse)(nil), // 1: imageservice.ListAvailableDatesResponse
	(*GetBandValuesRequest)(nil),       // 2: imageservice.GetBandValuesRequest
	(*GetBandValuesResponse)(nil),      // 3: imageservice.GetBandValuesResponse
	nil,                                // 4: imageservice.GetBandValuesResponse.BandDataEntry
}
var file_go_service_internal_ml_protobufs_image_service_proto_depIdxs = []int32{
	4, // 0: imageservice.GetBandValuesResponse.band_data:type_name -> imageservice.GetBandValuesResponse.BandDataEntry
	0, // 1: imageservice.ImageService.ListAvailableDates:input_type -> imageservice.ListAvailableDatesRequest
	2, // 2: imageservice.ImageService.GetBandValues:input_type -> imageservice.GetBandValuesRequest
	1, // 3: imageservice.ImageService.ListAvailableDates:output_type -> imageservice.ListAvailableDatesResponse
	3, // 4: imageservice.ImageService.GetBandValues:output_type -> imageservice.GetBandValuesResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_go_service_internal_ml_protobufs_image_service_proto_init() }
func file_go_service_internal_ml_protobufs_image_service_proto_init() {
	if File_go_service_internal_ml_protobufs_image_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_service_internal_ml_protobufs_image_service_proto_rawDesc), len(file_go_service_internal_ml_protobufs_image_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_service_internal_ml_protobufs_image_service_proto_goTypes,
		DependencyIndexes: file_go_service_internal_ml_protobufs_image_service_proto_depIdxs,
		MessageInfos:      file_go_service_internal_ml_protobufs_image_service_proto_msgTypes,
	}.Build()
	File_go_service_internal_ml_protobufs_image_service_proto = out.File
	file_go_service_internal_ml_protobufs_image_service_proto_goTypes = nil
	file_go_service_internal_ml_protobufs_image_service_proto_depIdxs = nil
}
