// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/ml/protobufs/plot_pixels.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pixel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pixel) Reset() {
	*x = Pixel{}
	mi := &file_internal_ml_protobufs_plot_pixels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pixel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pixel) ProtoMessage() {}

func (x *Pixel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ml_protobufs_plot_pixels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pixel.ProtoReflect.Descriptor instead.
func (*Pixel) Descriptor() ([]byte, []int) {
	return file_internal_ml_protobufs_plot_pixels_proto_rawDescGZIP(), []int{0}
}

func (x *Pixel) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pixel) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlotPixelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NDVI          map[string]float64     `protobuf:"bytes,1,rep,name=NDVI,proto3" json:"NDVI,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	NDRE          map[string]float64     `protobuf:"bytes,2,rep,name=NDRE,proto3" json:"NDRE,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	NDMI          map[string]float64     `protobuf:"bytes,3,rep,name=NDMI,proto3" json:"NDMI,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Pixels        []*Pixel               `protobuf:"bytes,4,rep,name=pixels,proto3" json:"pixels,omitempty"`
	ForestName    string                 `protobuf:"bytes,5,opt,name=forest_name,json=forestName,proto3" json:"forest_name,omitempty"`
	PlotId        string                 `protobuf:"bytes,6,opt,name=plot_id,json=plotId,proto3" json:"plot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotPixelsRequest) Reset() {
	*x = PlotPixelsRequest{}
	mi := &file_internal_ml_protobufs_plot_pixels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotPixelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotPixelsRequest) ProtoMessage() {}

func (x *PlotPixelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ml_protobufs_plot_pixels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotPixelsRequest.ProtoReflect.Descriptor instead.
func (*PlotPixelsRequest) Descriptor() ([]byte, []int) {
	return file_internal_ml_protobufs_plot_pixels_proto_rawDescGZIP(), []int{1}
}

func (x *PlotPixelsRequest) GetNDVI() map[string]float64 {
	if x != nil {
		return x.NDVI
	}
	return nil
}

func (x *PlotPixelsRequest) GetNDRE() map[string]float64 {
	if x != nil {
		return x.NDRE
	}
	return nil
}

func (x *PlotPixelsRequest) GetNDMI() map[string]float64 {
	if x != nil {
		return x.NDMI
	}
	return nil
}

func (x *PlotPixelsRequest) GetPixels() []*Pixel {
	if x != nil {
		return x.Pixels
	}
	return nil
}

func (x *PlotPixelsRequest) GetForestName() string {
	if x != nil {
		return x.ForestName
	}
	return ""
}

func (x *PlotPixelsRequest) GetPlotId() string {
	if x != nil {
		return x.PlotId
	}
	return ""
}

type PlotPixelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlotPixelsResponse) Reset() {
	*x = PlotPixelsResponse{}
	mi := &file_internal_ml_protobufs_plot_pixels_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlotPixelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlotPixelsResponse) ProtoMessage() {}

func (x *PlotPixelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ml_protobufs_plot_pixels_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlotPixelsResponse.ProtoReflect.Descriptor instead.
func (*PlotPixelsResponse) Descriptor() ([]byte, []int) {
	return file_internal_ml_protobufs_plot_pixels_proto_rawDescGZIP(), []int{2}
}

func (x *PlotPixelsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_ml_protobufs_plot_pixels_proto protoreflect.FileDescriptor

const file_internal_ml_protobufs_plot_pixels_proto_rawDesc = "" +
	"\n" +
	"'internal/ml/protobufs/plot_pixels.proto\x12\x02ml\"#\n" +
	"\x05Pixel\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xba\x03\n" +
	"\x11PlotPixelsRequest\x123\n" +
	"\x04NDVI\x18\x01 \x03(\v2\x1f.ml.PlotPixelsRequest.NDVIEntryR\x04NDVI\x123\n" +
	"\x04NDRE\x18\x02 \x03(\v2\x1f.ml.PlotPixelsRequest.NDREEntryR\x04NDRE\x123\n" +
	"\x04NDMI\x18\x03 \x03(\v2\x1f.ml.PlotPixelsRequest.NDMIEntryR\x04NDMI\x12!\n" +
	"\x06pixels\x18\x04 \x03(\v2\t.ml.PixelR\x06pixels\x12\x1f\n" +
	"\vforest_name\x18\x05 \x01(\tR\n" +
	"forestName\x12\x17\n" +
	"\aplot_id\x18\x06 \x01(\tR\x06plotId\x1a7\n" +
	"\tNDVIEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a7\n" +
	"\tNDREEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a7\n" +
	"\tNDMIEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\".\n" +
	"\x12PlotPixelsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2P\n" +
	"\x11PlotPixelsService\x12;\n" +
	"\n" +
	"PlotPixels\x12\x15.ml.PlotPixelsRequest\x1a\x16.ml.PlotPixelsResponseBTZRgithub.com/forest-guardian/forest-guardian-api-poc/internal/ml/protobufs;protobufsb\x06proto3"

var (
	file_internal_ml_protobufs_plot_pixels_proto_rawDescOnce sync.Once
	file_internal_ml_protobufs_plot_pixels_proto_rawDescData []byte
)

func file_internal_ml_protobufs_plot_pixels_proto_rawDescGZIP() []byte {
	file_internal_ml_protobufs_plot_pixels_proto_rawDescOnce.Do(func() {
		file_internal_ml_protobufs_plot_pixels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_ml_protobufs_plot_pixels_proto_rawDesc), len(file_internal_ml_protobufs_plot_pixels_proto_rawDesc)))
	})
	return file_internal_ml_protobufs_plot_pixels_proto_rawDescData
}

var file_internal_ml_protobufs_plot_pixels_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_ml_protobufs_plot_pixels_proto_goTypes = []any{
	(*Pixel)(nil),              // 0: ml.Pixel
	(*PlotPixelsRequest)(nil),  // 1: ml.PlotPixelsRequest
	(*PlotPixelsResponse)(nil), // 2: ml.PlotPixelsResponse
	nil,                        // 3: ml.PlotPixelsRequest.NDVIEntry
	nil,                        // 4: ml.PlotPixelsRequest.NDREEntry
	nil,                        // 5: ml.PlotPixelsRequest.NDMIEntry
}
var file_internal_ml_protobufs_plot_pixels_proto_depIdxs = []int32{
	3, // 0: ml.PlotPixelsRequest.NDVI:type_name -> ml.PlotPixelsRequest.NDVIEntry
	4, // 1: ml.PlotPixelsRequest.NDRE:type_name -> ml.PlotPixelsRequest.NDREEntry
	5, // 2: ml.PlotPixelsRequest.NDMI:type_name -> ml.PlotPixelsRequest.NDMIEntry
	0, // 3: ml.PlotPixelsRequest.pixels:type_name -> ml.Pixel
	1, // 4: ml.PlotPixelsService.PlotPixels:input_type -> ml.PlotPixelsRequest
	2, // 5: ml.PlotPixelsService.PlotPixels:output_type -> ml.PlotPixelsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_ml_protobufs_plot_pixels_proto_init() }
func file_internal_ml_protobufs_plot_pixels_proto_init() {
	if File_internal_ml_protobufs_plot_pixels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_ml_protobufs_plot_pixels_proto_rawDesc), len(file_internal_ml_protobufs_plot_pixels_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_ml_protobufs_plot_pixels_proto_goTypes,
		DependencyIndexes: file_internal_ml_protobufs_plot_pixels_proto_depIdxs,
		MessageInfos:      file_internal_ml_protobufs_plot_pixels_proto_msgTypes,
	}.Build()
	File_internal_ml_protobufs_plot_pixels_proto = out.File
	file_internal_ml_protobufs_plot_pixels_proto_goTypes = nil
	file_internal_ml_protobufs_plot_pixels_proto_depIdxs = nil
}
