// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/ml/run_model.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunModelService_RunModel_FullMethodName = "/RunModelService/RunModel"
)

// RunModelServiceClient is the client API for RunModelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunModelServiceClient interface {
	RunModel(ctx context.Context, in *RunModelRequest, opts ...grpc.CallOption) (*RunModelResponse, error)
}

type runModelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRunModelServiceClient(cc grpc.ClientConnInterface) RunModelServiceClient {
	return &runModelServiceClient{cc}
}

func (c *runModelServiceClient) RunModel(ctx context.Context, in *RunModelRequest, opts ...grpc.CallOption) (*RunModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunModelResponse)
	err := c.cc.Invoke(ctx, RunModelService_RunModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunModelServiceServer is the server API for RunModelService service.
// All implementations must embed UnimplementedRunModelServiceServer
// for forward compatibility.
type RunModelServiceServer interface {
	RunModel(context.Context, *RunModelRequest) (*RunModelResponse, error)
	mustEmbedUnimplementedRunModelServiceServer()
}

// UnimplementedRunModelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunModelServiceServer struct{}

func (UnimplementedRunModelServiceServer) RunModel(context.Context, *RunModelRequest) (*RunModelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunModel not implemented")
}
func (UnimplementedRunModelServiceServer) mustEmbedUnimplementedRunModelServiceServer() {}
func (UnimplementedRunModelServiceServer) testEmbeddedByValue()                         {}

// UnsafeRunModelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunModelServiceServer will
// result in compilation errors.
type UnsafeRunModelServiceServer interface {
	mustEmbedUnimplementedRunModelServiceServer()
}

func RegisterRunModelServiceServer(s grpc.ServiceRegistrar, srv RunModelServiceServer) {
	// If the following call pancis, it indicates UnimplementedRunModelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunModelService_ServiceDesc, srv)
}

func _RunModelService_RunModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunModelServiceServer).RunModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunModelService_RunModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunModelServiceServer).RunModel(ctx, req.(*RunModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RunModelService_ServiceDesc is the grpc.ServiceDesc for RunModelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunModelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RunModelService",
	HandlerType: (*RunModelServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunModel",
			Handler:    _RunModelService_RunModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/ml/run_model.proto",
}
