# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: gam_smoothing.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'gam_smoothing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13gam_smoothing.proto\",\n\rSmoothRequest\x12\x0e\n\x06values\x18\x01 \x03(\x01\x12\x0b\n\x03lam\x18\x02 \x01(\x01\")\n\x0eSmoothResponse\x12\x17\n\x0fsmoothed_values\x18\x01 \x03(\x01\x32@\n\x13GamSmoothingService\x12)\n\x06Smooth\x12\x0e.SmoothRequest\x1a\x0f.SmoothResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gam_smoothing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SMOOTHREQUEST']._serialized_start=23
  _globals['_SMOOTHREQUEST']._serialized_end=67
  _globals['_SMOOTHRESPONSE']._serialized_start=69
  _globals['_SMOOTHRESPONSE']._serialized_end=110
  _globals['_GAMSMOOTHINGSERVICE']._serialized_start=112
  _globals['_GAMSMOOTHINGSERVICE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
