// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: clear_and_smooth.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClearAndSmoothRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []float64              `protobuf:"fixed64,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAndSmoothRequest) Reset() {
	*x = ClearAndSmoothRequest{}
	mi := &file_clear_and_smooth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAndSmoothRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAndSmoothRequest) ProtoMessage() {}

func (x *ClearAndSmoothRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clear_and_smooth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAndSmoothRequest.ProtoReflect.Descriptor instead.
func (*ClearAndSmoothRequest) Descriptor() ([]byte, []int) {
	return file_clear_and_smooth_proto_rawDescGZIP(), []int{0}
}

func (x *ClearAndSmoothRequest) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClearAndSmoothResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SmoothedData  []float64              `protobuf:"fixed64,1,rep,packed,name=smoothed_data,json=smoothedData,proto3" json:"smoothed_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAndSmoothResponse) Reset() {
	*x = ClearAndSmoothResponse{}
	mi := &file_clear_and_smooth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAndSmoothResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAndSmoothResponse) ProtoMessage() {}

func (x *ClearAndSmoothResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clear_and_smooth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAndSmoothResponse.ProtoReflect.Descriptor instead.
func (*ClearAndSmoothResponse) Descriptor() ([]byte, []int) {
	return file_clear_and_smooth_proto_rawDescGZIP(), []int{1}
}

func (x *ClearAndSmoothResponse) GetSmoothedData() []float64 {
	if x != nil {
		return x.SmoothedData
	}
	return nil
}

var File_clear_and_smooth_proto protoreflect.FileDescriptor

const file_clear_and_smooth_proto_rawDesc = "" +
	"\n" +
	"\x16clear_and_smooth.proto\"+\n" +
	"\x15ClearAndSmoothRequest\x12\x12\n" +
	"\x04data\x18\x01 \x03(\x01R\x04data\"=\n" +
	"\x16ClearAndSmoothResponse\x12#\n" +
	"\rsmoothed_data\x18\x01 \x03(\x01R\fsmoothedData2Z\n" +
	"\x15ClearAndSmoothService\x12A\n" +
	"\x0eClearAndSmooth\x12\x16.ClearAndSmoothRequest\x1a\x17.ClearAndSmoothResponseB\fZ\n" +
	"/protobufsb\x06proto3"

var (
	file_clear_and_smooth_proto_rawDescOnce sync.Once
	file_clear_and_smooth_proto_rawDescData []byte
)

func file_clear_and_smooth_proto_rawDescGZIP() []byte {
	file_clear_and_smooth_proto_rawDescOnce.Do(func() {
		file_clear_and_smooth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clear_and_smooth_proto_rawDesc), len(file_clear_and_smooth_proto_rawDesc)))
	})
	return file_clear_and_smooth_proto_rawDescData
}

var file_clear_and_smooth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clear_and_smooth_proto_goTypes = []any{
	(*ClearAndSmoothRequest)(nil),  // 0: ClearAndSmoothRequest
	(*ClearAndSmoothResponse)(nil), // 1: ClearAndSmoothResponse
}
var file_clear_and_smooth_proto_depIdxs = []int32{
	0, // 0: ClearAndSmoothService.ClearAndSmooth:input_type -> ClearAndSmoothRequest
	1, // 1: ClearAndSmoothService.ClearAndSmooth:output_type -> ClearAndSmoothResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clear_and_smooth_proto_init() }
func file_clear_and_smooth_proto_init() {
	if File_clear_and_smooth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clear_and_smooth_proto_rawDesc), len(file_clear_and_smooth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clear_and_smooth_proto_goTypes,
		DependencyIndexes: file_clear_and_smooth_proto_depIdxs,
		MessageInfos:      file_clear_and_smooth_proto_msgTypes,
	}.Build()
	File_clear_and_smooth_proto = out.File
	file_clear_and_smooth_proto_goTypes = nil
	file_clear_and_smooth_proto_depIdxs = nil
}
