// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: python-service/clear_and_smooth.proto

package protobufs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClearAndSmoothRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]*DoubleList `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAndSmoothRequest) Reset() {
	*x = ClearAndSmoothRequest{}
	mi := &file_python_service_clear_and_smooth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAndSmoothRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAndSmoothRequest) ProtoMessage() {}

func (x *ClearAndSmoothRequest) ProtoReflect() protoreflect.Message {
	mi := &file_python_service_clear_and_smooth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAndSmoothRequest.ProtoReflect.Descriptor instead.
func (*ClearAndSmoothRequest) Descriptor() ([]byte, []int) {
	return file_python_service_clear_and_smooth_proto_rawDescGZIP(), []int{0}
}

func (x *ClearAndSmoothRequest) GetData() map[string]*DoubleList {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClearAndSmoothResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SmoothedData  map[string]*DoubleList `protobuf:"bytes,1,rep,name=smoothed_data,json=smoothedData,proto3" json:"smoothed_data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearAndSmoothResponse) Reset() {
	*x = ClearAndSmoothResponse{}
	mi := &file_python_service_clear_and_smooth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearAndSmoothResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearAndSmoothResponse) ProtoMessage() {}

func (x *ClearAndSmoothResponse) ProtoReflect() protoreflect.Message {
	mi := &file_python_service_clear_and_smooth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearAndSmoothResponse.ProtoReflect.Descriptor instead.
func (*ClearAndSmoothResponse) Descriptor() ([]byte, []int) {
	return file_python_service_clear_and_smooth_proto_rawDescGZIP(), []int{1}
}

func (x *ClearAndSmoothResponse) GetSmoothedData() map[string]*DoubleList {
	if x != nil {
		return x.SmoothedData
	}
	return nil
}

type DoubleList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoubleList) Reset() {
	*x = DoubleList{}
	mi := &file_python_service_clear_and_smooth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoubleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoubleList) ProtoMessage() {}

func (x *DoubleList) ProtoReflect() protoreflect.Message {
	mi := &file_python_service_clear_and_smooth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoubleList.ProtoReflect.Descriptor instead.
func (*DoubleList) Descriptor() ([]byte, []int) {
	return file_python_service_clear_and_smooth_proto_rawDescGZIP(), []int{2}
}

func (x *DoubleList) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_python_service_clear_and_smooth_proto protoreflect.FileDescriptor

const file_python_service_clear_and_smooth_proto_rawDesc = "" +
	"\n" +
	"%python-service/clear_and_smooth.proto\"\x93\x01\n" +
	"\x15ClearAndSmoothRequest\x124\n" +
	"\x04data\x18\x01 \x03(\v2 .ClearAndSmoothRequest.DataEntryR\x04data\x1aD\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.DoubleListR\x05value:\x028\x01\"\xb6\x01\n" +
	"\x16ClearAndSmoothResponse\x12N\n" +
	"\rsmoothed_data\x18\x01 \x03(\v2).ClearAndSmoothResponse.SmoothedDataEntryR\fsmoothedData\x1aL\n" +
	"\x11SmoothedDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.DoubleListR\x05value:\x028\x01\"$\n" +
	"\n" +
	"DoubleList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values2Z\n" +
	"\x15ClearAndSmoothService\x12A\n" +
	"\x0eClearAndSmooth\x12\x16.ClearAndSmoothRequest\x1a\x17.ClearAndSmoothResponseBMZKgithub.com/forest-guardian/forest-guardian-api-poc/internal/delta/protobufsb\x06proto3"

var (
	file_python_service_clear_and_smooth_proto_rawDescOnce sync.Once
	file_python_service_clear_and_smooth_proto_rawDescData []byte
)

func file_python_service_clear_and_smooth_proto_rawDescGZIP() []byte {
	file_python_service_clear_and_smooth_proto_rawDescOnce.Do(func() {
		file_python_service_clear_and_smooth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_python_service_clear_and_smooth_proto_rawDesc), len(file_python_service_clear_and_smooth_proto_rawDesc)))
	})
	return file_python_service_clear_and_smooth_proto_rawDescData
}

var file_python_service_clear_and_smooth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_python_service_clear_and_smooth_proto_goTypes = []any{
	(*ClearAndSmoothRequest)(nil),  // 0: ClearAndSmoothRequest
	(*ClearAndSmoothResponse)(nil), // 1: ClearAndSmoothResponse
	(*DoubleList)(nil),             // 2: DoubleList
	nil,                            // 3: ClearAndSmoothRequest.DataEntry
	nil,                            // 4: ClearAndSmoothResponse.SmoothedDataEntry
}
var file_python_service_clear_and_smooth_proto_depIdxs = []int32{
	3, // 0: ClearAndSmoothRequest.data:type_name -> ClearAndSmoothRequest.DataEntry
	4, // 1: ClearAndSmoothResponse.smoothed_data:type_name -> ClearAndSmoothResponse.SmoothedDataEntry
	2, // 2: ClearAndSmoothRequest.DataEntry.value:type_name -> DoubleList
	2, // 3: ClearAndSmoothResponse.SmoothedDataEntry.value:type_name -> DoubleList
	0, // 4: ClearAndSmoothService.ClearAndSmooth:input_type -> ClearAndSmoothRequest
	1, // 5: ClearAndSmoothService.ClearAndSmooth:output_type -> ClearAndSmoothResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_python_service_clear_and_smooth_proto_init() }
func file_python_service_clear_and_smooth_proto_init() {
	if File_python_service_clear_and_smooth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_python_service_clear_and_smooth_proto_rawDesc), len(file_python_service_clear_and_smooth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_python_service_clear_and_smooth_proto_goTypes,
		DependencyIndexes: file_python_service_clear_and_smooth_proto_depIdxs,
		MessageInfos:      file_python_service_clear_and_smooth_proto_msgTypes,
	}.Build()
	File_python_service_clear_and_smooth_proto = out.File
	file_python_service_clear_and_smooth_proto_goTypes = nil
	file_python_service_clear_and_smooth_proto_depIdxs = nil
}
