// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: python-service/clear_and_smooth.proto

package protobufs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClearAndSmoothService_ClearAndSmooth_FullMethodName = "/ClearAndSmoothService/ClearAndSmooth"
)

// ClearAndSmoothServiceClient is the client API for ClearAndSmoothService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClearAndSmoothServiceClient interface {
	ClearAndSmooth(ctx context.Context, in *ClearAndSmoothRequest, opts ...grpc.CallOption) (*ClearAndSmoothResponse, error)
}

type clearAndSmoothServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClearAndSmoothServiceClient(cc grpc.ClientConnInterface) ClearAndSmoothServiceClient {
	return &clearAndSmoothServiceClient{cc}
}

func (c *clearAndSmoothServiceClient) ClearAndSmooth(ctx context.Context, in *ClearAndSmoothRequest, opts ...grpc.CallOption) (*ClearAndSmoothResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearAndSmoothResponse)
	err := c.cc.Invoke(ctx, ClearAndSmoothService_ClearAndSmooth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClearAndSmoothServiceServer is the server API for ClearAndSmoothService service.
// All implementations must embed UnimplementedClearAndSmoothServiceServer
// for forward compatibility.
type ClearAndSmoothServiceServer interface {
	ClearAndSmooth(context.Context, *ClearAndSmoothRequest) (*ClearAndSmoothResponse, error)
	mustEmbedUnimplementedClearAndSmoothServiceServer()
}

// UnimplementedClearAndSmoothServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClearAndSmoothServiceServer struct{}

func (UnimplementedClearAndSmoothServiceServer) ClearAndSmooth(context.Context, *ClearAndSmoothRequest) (*ClearAndSmoothResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearAndSmooth not implemented")
}
func (UnimplementedClearAndSmoothServiceServer) mustEmbedUnimplementedClearAndSmoothServiceServer() {}
func (UnimplementedClearAndSmoothServiceServer) testEmbeddedByValue()                               {}

// UnsafeClearAndSmoothServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClearAndSmoothServiceServer will
// result in compilation errors.
type UnsafeClearAndSmoothServiceServer interface {
	mustEmbedUnimplementedClearAndSmoothServiceServer()
}

func RegisterClearAndSmoothServiceServer(s grpc.ServiceRegistrar, srv ClearAndSmoothServiceServer) {
	// If the following call pancis, it indicates UnimplementedClearAndSmoothServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClearAndSmoothService_ServiceDesc, srv)
}

func _ClearAndSmoothService_ClearAndSmooth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearAndSmoothRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClearAndSmoothServiceServer).ClearAndSmooth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClearAndSmoothService_ClearAndSmooth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClearAndSmoothServiceServer).ClearAndSmooth(ctx, req.(*ClearAndSmoothRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClearAndSmoothService_ServiceDesc is the grpc.ServiceDesc for ClearAndSmoothService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClearAndSmoothService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ClearAndSmoothService",
	HandlerType: (*ClearAndSmoothServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClearAndSmooth",
			Handler:    _ClearAndSmoothService_ClearAndSmooth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "python-service/clear_and_smooth.proto",
}
