// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/ml/protobufs/pest_clustering.proto

package protobufs

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeltaData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Forest         string                 `protobuf:"bytes,1,opt,name=forest,proto3" json:"forest,omitempty"`
	Plot           string                 `protobuf:"bytes,2,opt,name=plot,proto3" json:"plot,omitempty"`
	DeltaMin       int32                  `protobuf:"varint,3,opt,name=delta_min,json=deltaMin,proto3" json:"delta_min,omitempty"`
	DeltaMax       int32                  `protobuf:"varint,4,opt,name=delta_max,json=deltaMax,proto3" json:"delta_max,omitempty"`
	Delta          int32                  `protobuf:"varint,5,opt,name=delta,proto3" json:"delta,omitempty"`
	StartDate      string                 `protobuf:"bytes,6,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate        string                 `protobuf:"bytes,7,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	X              int32                  `protobuf:"varint,8,opt,name=x,proto3" json:"x,omitempty"`
	Y              int32                  `protobuf:"varint,9,opt,name=y,proto3" json:"y,omitempty"`
	Ndre           float64                `protobuf:"fixed64,10,opt,name=ndre,proto3" json:"ndre,omitempty"`
	Ndmi           float64                `protobuf:"fixed64,11,opt,name=ndmi,proto3" json:"ndmi,omitempty"`
	Psri           float64                `protobuf:"fixed64,12,opt,name=psri,proto3" json:"psri,omitempty"`
	Ndvi           float64                `protobuf:"fixed64,13,opt,name=ndvi,proto3" json:"ndvi,omitempty"`
	NdreDerivative float64                `protobuf:"fixed64,14,opt,name=ndre_derivative,json=ndreDerivative,proto3" json:"ndre_derivative,omitempty"`
	NdmiDerivative float64                `protobuf:"fixed64,15,opt,name=ndmi_derivative,json=ndmiDerivative,proto3" json:"ndmi_derivative,omitempty"`
	PsriDerivative float64                `protobuf:"fixed64,16,opt,name=psri_derivative,json=psriDerivative,proto3" json:"psri_derivative,omitempty"`
	NdviDerivative float64                `protobuf:"fixed64,17,opt,name=ndvi_derivative,json=ndviDerivative,proto3" json:"ndvi_derivative,omitempty"`
	Label          string                 `protobuf:"bytes,18,opt,name=label,proto3" json:"label,omitempty"`
	Latitude       float64                `protobuf:"fixed64,19,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude      float64                `protobuf:"fixed64,20,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeltaData) Reset() {
	*x = DeltaData{}
	mi := &file_internal_ml_protobufs_pest_clustering_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaData) ProtoMessage() {}

func (x *DeltaData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ml_protobufs_pest_clustering_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaData.ProtoReflect.Descriptor instead.
func (*DeltaData) Descriptor() ([]byte, []int) {
	return file_internal_ml_protobufs_pest_clustering_proto_rawDescGZIP(), []int{0}
}

func (x *DeltaData) GetFarm() string {
	if x != nil {
		return x.Forest
	}
	return ""
}

func (x *DeltaData) GetPlot() string {
	if x != nil {
		return x.Plot
	}
	return ""
}

func (x *DeltaData) GetDeltaMin() int32 {
	if x != nil {
		return x.DeltaMin
	}
	return 0
}

func (x *DeltaData) GetDeltaMax() int32 {
	if x != nil {
		return x.DeltaMax
	}
	return 0
}

func (x *DeltaData) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *DeltaData) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *DeltaData) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *DeltaData) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *DeltaData) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *DeltaData) GetNdre() float64 {
	if x != nil {
		return x.Ndre
	}
	return 0
}

func (x *DeltaData) GetNdmi() float64 {
	if x != nil {
		return x.Ndmi
	}
	return 0
}

func (x *DeltaData) GetPsri() float64 {
	if x != nil {
		return x.Psri
	}
	return 0
}

func (x *DeltaData) GetNdvi() float64 {
	if x != nil {
		return x.Ndvi
	}
	return 0
}

func (x *DeltaData) GetNdreDerivative() float64 {
	if x != nil {
		return x.NdreDerivative
	}
	return 0
}

func (x *DeltaData) GetNdmiDerivative() float64 {
	if x != nil {
		return x.NdmiDerivative
	}
	return 0
}

func (x *DeltaData) GetPsriDerivative() float64 {
	if x != nil {
		return x.PsriDerivative
	}
	return 0
}

func (x *DeltaData) GetNdviDerivative() float64 {
	if x != nil {
		return x.NdviDerivative
	}
	return 0
}

func (x *DeltaData) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *DeltaData) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *DeltaData) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type PestSpreadSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *DeltaData             `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Cluster       int32                  `protobuf:"varint,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PestSpreadSample) Reset() {
	*x = PestSpreadSample{}
	mi := &file_internal_ml_protobufs_pest_clustering_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PestSpreadSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PestSpreadSample) ProtoMessage() {}

func (x *PestSpreadSample) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ml_protobufs_pest_clustering_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PestSpreadSample.ProtoReflect.Descriptor instead.
func (*PestSpreadSample) Descriptor() ([]byte, []int) {
	return file_internal_ml_protobufs_pest_clustering_proto_rawDescGZIP(), []int{1}
}

func (x *PestSpreadSample) GetData() *DeltaData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PestSpreadSample) GetCluster() int32 {
	if x != nil {
		return x.Cluster
	}
	return 0
}

type ClusterizeSpreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeltaData     []*DeltaData           `protobuf:"bytes,1,rep,name=delta_data,json=deltaData,proto3" json:"delta_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterizeSpreadRequest) Reset() {
	*x = ClusterizeSpreadRequest{}
	mi := &file_internal_ml_protobufs_pest_clustering_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterizeSpreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterizeSpreadRequest) ProtoMessage() {}

func (x *ClusterizeSpreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ml_protobufs_pest_clustering_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterizeSpreadRequest.ProtoReflect.Descriptor instead.
func (*ClusterizeSpreadRequest) Descriptor() ([]byte, []int) {
	return file_internal_ml_protobufs_pest_clustering_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterizeSpreadRequest) GetDeltaData() []*DeltaData {
	if x != nil {
		return x.DeltaData
	}
	return nil
}

type ClusterizeSpreadResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PestSpreadSamples []*PestSpreadSample    `protobuf:"bytes,1,rep,name=pest_spread_samples,json=pestSpreadSamples,proto3" json:"pest_spread_samples,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClusterizeSpreadResponse) Reset() {
	*x = ClusterizeSpreadResponse{}
	mi := &file_internal_ml_protobufs_pest_clustering_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterizeSpreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterizeSpreadResponse) ProtoMessage() {}

func (x *ClusterizeSpreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ml_protobufs_pest_clustering_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterizeSpreadResponse.ProtoReflect.Descriptor instead.
func (*ClusterizeSpreadResponse) Descriptor() ([]byte, []int) {
	return file_internal_ml_protobufs_pest_clustering_proto_rawDescGZIP(), []int{3}
}

func (x *ClusterizeSpreadResponse) GetPestSpreadSamples() []*PestSpreadSample {
	if x != nil {
		return x.PestSpreadSamples
	}
	return nil
}

var File_internal_ml_protobufs_pest_clustering_proto protoreflect.FileDescriptor

const file_internal_ml_protobufs_pest_clustering_proto_rawDesc = "" +
	"\n" +
	"+internal/ml/protobufs/pest_clustering.proto\"\x9d\x04\n" +
	"\tDeltaData\x12\x12\n" +
	"\x04farm\x18\x01 \x01(\tR\x04farm\x12\x12\n" +
	"\x04plot\x18\x02 \x01(\tR\x04plot\x12\x1b\n" +
	"\tdelta_min\x18\x03 \x01(\x05R\bdeltaMin\x12\x1b\n" +
	"\tdelta_max\x18\x04 \x01(\x05R\bdeltaMax\x12\x14\n" +
	"\x05delta\x18\x05 \x01(\x05R\x05delta\x12\x1d\n" +
	"\n" +
	"start_date\x18\x06 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\a \x01(\tR\aendDate\x12\f\n" +
	"\x01x\x18\b \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\t \x01(\x05R\x01y\x12\x12\n" +
	"\x04ndre\x18\n" +
	" \x01(\x01R\x04ndre\x12\x12\n" +
	"\x04ndmi\x18\v \x01(\x01R\x04ndmi\x12\x12\n" +
	"\x04psri\x18\f \x01(\x01R\x04psri\x12\x12\n" +
	"\x04ndvi\x18\r \x01(\x01R\x04ndvi\x12'\n" +
	"\x0fndre_derivative\x18\x0e \x01(\x01R\x0endreDerivative\x12'\n" +
	"\x0fndmi_derivative\x18\x0f \x01(\x01R\x0endmiDerivative\x12'\n" +
	"\x0fpsri_derivative\x18\x10 \x01(\x01R\x0epsriDerivative\x12'\n" +
	"\x0fndvi_derivative\x18\x11 \x01(\x01R\x0endviDerivative\x12\x14\n" +
	"\x05label\x18\x12 \x01(\tR\x05label\x12\x1a\n" +
	"\blatitude\x18\x13 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x14 \x01(\x01R\tlongitude\"L\n" +
	"\x10PestSpreadSample\x12\x1e\n" +
	"\x04data\x18\x01 \x01(\v2\n" +
	".DeltaDataR\x04data\x12\x18\n" +
	"\acluster\x18\x02 \x01(\x05R\acluster\"D\n" +
	"\x17ClusterizeSpreadRequest\x12)\n" +
	"\n" +
	"delta_data\x18\x01 \x03(\v2\n" +
	".DeltaDataR\tdeltaData\"]\n" +
	"\x18ClusterizeSpreadResponse\x12A\n" +
	"\x13pest_spread_samples\x18\x01 \x03(\v2\x11.PestSpreadSampleR\x11pestSpreadSamples2`\n" +
	"\x15PestClusteringService\x12G\n" +
	"\x10ClusterizeSpread\x12\x18.ClusterizeSpreadRequest\x1a\x19.ClusterizeSpreadResponseB\fZ\n" +
	"/protobufsb\x06proto3"

var (
	file_internal_ml_protobufs_pest_clustering_proto_rawDescOnce sync.Once
	file_internal_ml_protobufs_pest_clustering_proto_rawDescData []byte
)

func file_internal_ml_protobufs_pest_clustering_proto_rawDescGZIP() []byte {
	file_internal_ml_protobufs_pest_clustering_proto_rawDescOnce.Do(func() {
		file_internal_ml_protobufs_pest_clustering_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_ml_protobufs_pest_clustering_proto_rawDesc), len(file_internal_ml_protobufs_pest_clustering_proto_rawDesc)))
	})
	return file_internal_ml_protobufs_pest_clustering_proto_rawDescData
}

var file_internal_ml_protobufs_pest_clustering_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_ml_protobufs_pest_clustering_proto_goTypes = []any{
	(*DeltaData)(nil),                // 0: DeltaData
	(*PestSpreadSample)(nil),         // 1: PestSpreadSample
	(*ClusterizeSpreadRequest)(nil),  // 2: ClusterizeSpreadRequest
	(*ClusterizeSpreadResponse)(nil), // 3: ClusterizeSpreadResponse
}
var file_internal_ml_protobufs_pest_clustering_proto_depIdxs = []int32{
	0, // 0: PestSpreadSample.data:type_name -> DeltaData
	0, // 1: ClusterizeSpreadRequest.delta_data:type_name -> DeltaData
	1, // 2: ClusterizeSpreadResponse.pest_spread_samples:type_name -> PestSpreadSample
	2, // 3: PestClusteringService.ClusterizeSpread:input_type -> ClusterizeSpreadRequest
	3, // 4: PestClusteringService.ClusterizeSpread:output_type -> ClusterizeSpreadResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_ml_protobufs_pest_clustering_proto_init() }
func file_internal_ml_protobufs_pest_clustering_proto_init() {
	if File_internal_ml_protobufs_pest_clustering_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_ml_protobufs_pest_clustering_proto_rawDesc), len(file_internal_ml_protobufs_pest_clustering_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_ml_protobufs_pest_clustering_proto_goTypes,
		DependencyIndexes: file_internal_ml_protobufs_pest_clustering_proto_depIdxs,
		MessageInfos:      file_internal_ml_protobufs_pest_clustering_proto_msgTypes,
	}.Build()
	File_internal_ml_protobufs_pest_clustering_proto = out.File
	file_internal_ml_protobufs_pest_clustering_proto_goTypes = nil
	file_internal_ml_protobufs_pest_clustering_proto_depIdxs = nil
}
